### ISSUE TITLE
Wireguard support (new VPN protocol)

### ISSUE THREAD

**Issue by t4777sd** [tasket/qubes-tunnel#1]
It would be nice if this supported wireguard as a protocol in addition to openvpn (I assume naming it "tunnel" and not "openVPN" is due to this intention). It has a smaller and more auditable code base than OpenVPN. It also uses more secure crypto primites by default. And, it will be integrated into the kernel directly. Lastly, it is faster than OpenVPN: https://www.wireguard.com/performance/

Azire, as they are helping to promote wireguard, is offering everyone a free wireguard vpn account: https://www.azirevpn.com/

**Comment by tasket** [comment]
Experimental service config for wg has already been added. See notes from twin project, https://github.com/tasket/Qubes-vpn-support#using-clients-other-than-openvpn
